<?php

namespace App\Console\Commands;

use App\Models\Rent;
use App\Models\TenancyAgreement;
use Carbon\Carbon;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Log;

class RentAutoGeneratedEveryMonth extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'rent:generate-due';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate rent entries after rent due day if not already created';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {

        $today = Carbon::today();
        $currentMonth = $today->month;
        $currentYear = $today->year;

        // GET ALL TENANCY AGREEMENTS FOR CURRENT MONTH AND YEAR
        $agreements = TenancyAgreement::with(['property', 'rents'])->get();

        // Log::info("All Agreements: {$agreements}");

        // SEND RENT DUE DATE REMINDER
        foreach ($agreements as $agreement) {
            // SKIP IF RENT DUE DATE IS NOT SET 
            if (!$agreement->rent_due_day) {
                continue;
            }
            // Log::info("Agreement have rent due date: {$agreement}");

            // Log::info("Rent created for Agreement ID: {$agreement}");
            // SKIP IF TENANT CONTRACT EXPIRED
            if (!$agreement->tenant_contact_expired_date || Carbon::parse($agreement->tenant_contact_expired_date)->lt($today)) {
                continue;
            }

            // BUILD RENT DUE DATE FOR CURRENT MONTH AND YEAR
            $rentDueDate = Carbon::createFromDate($currentYear, $currentMonth, $agreement->rent_due_day);


            // CHECK IF RENT DUE DATE IS PASSED AND RENT NOT CREATED YET
            if ($today->greaterThanOrEqualTo($rentDueDate)) {
                // SEND RENT DUE DATE REMINDER

                // CHECK IF RENT IS ALREADY CREATED FOR CURRENT MONTH AND YEAR
                $rentAlreadyExists = Rent::where('tenancy_agreement_id', $agreement->id)->where('year', $currentYear)->where('month', $currentMonth)->exists();

                // Log::info("Rent Already Exists: {$rentAlreadyExists}");
                // IF NOT CREATE RENT
                if (!$rentAlreadyExists) {
                    Log::info("Rent created for Agreement: {$agreement}");

                    // PREVIOUS MONTH
                    $previousMonth = Carbon::create($currentYear, $currentMonth, 1)->subMonth();

                    // PREVIOUS MONTH RENT
                    $previousMonthRent = Rent::where('tenancy_agreement_id', $agreement->id)
                        ->where('year', $previousMonth->year)
                        ->where('month', $previousMonth->month)
                        ->first();

                    // CALCULATE ARREAR
                    $arrear = 0;
                    if ($previousMonthRent && $previousMonthRent->payment_status !== "fully_paid") {
                        $arrear = $previousMonthRent->arrear;
                    }

                    // GET PROPERTY CREATOR
                    $createdBy = (int) optional($agreement->property)->created_by;

                    // CREATE NEW RECORD
                    Rent::create([
                        'tenancy_agreement_id' => $agreement->id,
                        'year' => $currentYear,
                        'month' => $currentMonth,
                        'rent_amount' => $agreement->agreed_rent,
                        'paid_amount' => 0,
                        'arrear' => $arrear,
                        'payment_status' => 'pending',
                        'payment_date' => "",
                        'payment_method' => "",
                        'rent_taken_by' => "",
                        'remarks' => 'This rent is auto generated and due on ' . $rentDueDate->toDateString(),
                        'created_by' => $createdBy,
                    ]);

                    // $this->info("Rent created for Agreement ID: {$agreement->id}");
                }
            }
        }
        return 0;
    }
}
