<?php

namespace App\Console\Commands;

use App\Models\Rent;
use App\Models\TenancyAgreement;
use Carbon\Carbon;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Log;

class RentAutoGeneratedEveryMonth extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'rent:generate-due';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate rent entries after rent due day if not already created';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        $today = Carbon::today();
        $currentMonth = $today->month;
        $currentYear = $today->year;

        // GET AGREEMENTS ONLY WHERE  PAYMENT OPTION -> per_calendar_month
        $agreements = TenancyAgreement::with(['property', 'rents'])
            ->where('rent_payment_option', 'per_calendar_month')
            ->whereHas('property', function ($query) {
                $query->whereNull('deleted_at');
            })
            ->whereNotNull('rent_due_day')
            ->whereNotNull('tenant_contact_expired_date')
            ->whereDate('tenant_contact_expired_date', '>', $today)
            ->get();

        // $this->info('Agreements: ' . json_encode($agreements->toArray(), JSON_PRETTY_PRINT));
        // echo json_encode($agreements->toArray(), JSON_PRETTY_PRINT);

        foreach ($agreements as $agreement) {
            // echo $agreement->property->name . "\n";
            // $this->info('Agreement: ' . json_encode($agreement, JSON_PRETTY_PRINT));
            // Current due date
            $rentDueDate = Carbon::createFromDate($currentYear, $currentMonth, $agreement->rent_due_day);

            // Skip if rent already created
            $rentAlreadyExists = Rent::where('tenancy_agreement_id', $agreement->id)
                ->where('year', $currentYear)
                ->where('month', $currentMonth)
                ->exists();

            // $this->info('rentAlreadyExists: ' . json_encode($rentAlreadyExists, JSON_PRETTY_PRINT));


            if ($today->gt($rentDueDate) && !$rentAlreadyExists) {
                $start = Carbon::parse($agreement->date_of_moving)->startOfMonth();
                $prevMonth = Carbon::create($currentYear, $currentMonth, 1)->subMonth()->startOfMonth();
                $contractEnd = Carbon::parse($agreement->tenant_contact_expired_date)->startOfMonth();

                // $this->info('Agreement: ' . json_encode($agreement, JSON_PRETTY_PRINT));

                // Use the lesser between prevMonth and contractEnd
                $effectiveEnd = $prevMonth->lt($contractEnd) ? $prevMonth : $contractEnd;

                // Calculate total months from start to previous month (inclusive)
                $months = $start->diffInMonths($effectiveEnd) + 1;

                // Final calculations
                $expectedTotal = $months * $agreement->agreed_rent;
                $paidTotal = $agreement->rents->sum('paid_amount');
                $arrear = ($expectedTotal - $paidTotal); // If negative that's mean it over paid


                $createdBy = (int) optional($agreement->property)->created_by;

                Rent::create([
                    'tenancy_agreement_id' => $agreement->id,
                    'year' => $currentYear,
                    'month' => $currentMonth,
                    'rent_amount' => $agreement->agreed_rent,
                    'paid_amount' => 0,
                    'arrear' => $arrear,
                    'payment_status' => 'pending',
                    'payment_date' => $rentDueDate,
                    'payment_method' => "",
                    'rent_taken_by' => "",
                    'remarks' => 'This rent is auto generated and due on ' . $rentDueDate->toDateString(),
                    'created_by' => $createdBy,
                ]);

                $this->info("Auto rent created for Agreement ID: {$agreement->id}, Arrear: {$arrear}");
            }
        }

        return 0;
    }
}
