---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mughalsign/public_html/garage-management2
    - /bin/cp -r * $DEPLOYPATH #copy all from root
    - /bin/cp -R .env $DEPLOYPATH
    - /bin/cp -R .htaccess $DEPLOYPATH
